// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpacePark.DatabaseModels;

namespace SpacePark.Migrations
{
    [DbContext(typeof(SpaceParkContext))]
    [Migration("20200325152548_nulltoshipoid")]
    partial class nulltoshipoid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpacePark.ParkingLot", b =>
                {
                    b.Property<int>("ParkingLotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("SpaceShipID")
                        .HasColumnType("int");

                    b.HasKey("ParkingLotID");

                    b.HasIndex("SpaceShipID");

                    b.ToTable("ParkingLot");
                });

            modelBuilder.Entity("SpacePark.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpaceShipID")
                        .HasColumnType("int");

                    b.HasKey("PersonID");

                    b.HasIndex("SpaceShipID")
                        .IsUnique()
                        .HasFilter("[SpaceShipID] IS NOT NULL");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SpacePark.SpaceShip", b =>
                {
                    b.Property<int>("SpaceShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpaceShipID");

                    b.ToTable("SpaceShips");
                });

            modelBuilder.Entity("SpacePark.ParkingLot", b =>
                {
                    b.HasOne("SpacePark.SpaceShip", "SpaceShip")
                        .WithMany()
                        .HasForeignKey("SpaceShipID");
                });

            modelBuilder.Entity("SpacePark.Person", b =>
                {
                    b.HasOne("SpacePark.SpaceShip", "CurrentShip")
                        .WithOne("PersonID")
                        .HasForeignKey("SpacePark.Person", "SpaceShipID");
                });
#pragma warning restore 612, 618
        }
    }
}
